source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target 'MasonryExtend_Example' do
  pod 'MasonryExtend', :path => '../'

  target 'MasonryExtend_Tests' do
    inherit! :search_paths

    
  end
end
